config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :services

  root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord

  def self.curl(project)
    resp = `curl -Is #{project.address} -L | grep HTTP/`
    resp.include?("204") || resp.include?("200") || resp.include("201")
  end

end

# return false if (ping.include?("Found") || ping.include?("ERROR"))
# return ping.include?(project.address)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] if params[:locale].present?
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :address, :rvm_list, :gemset)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:read]


  def index
    require 'net/ping'
    todos_projetos = Project.all
    @status = Hash.new
    # raise Project.all.inspect
    Net::Ping::TCP.econnrefused = true
    @status = Hash.new

    Project.all.each do |p|
      @status[p.project_name.to_sym] = Service.curl(p)
    end

    
    


    # raise teste.inspect




    # @status = Hash.new
    # todos_projetos = Project.where(id: 7)

    # todos_projetos = Project.all

    # # raise todos_projetos.inspect
    
    # todos_projetos.each do |projeto|
    #   @status[projeto.project_name.to_sym] = Service.servidor_online(projeto)
    # end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:projects, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Plataforma RVM PGE</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Plataforma RVM PGE", "/projects", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to "Serviços", services_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :project_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rvm_list, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :rvm_list, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gemset, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :gemset, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @project, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/v4-shims.css">
</head>
<div class="page-header">
  <%= link_to new_project_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Project
  <% end %>
  <h1>Listing projects</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Project name</th>
            <th>Address</th>
            <th>Rvm</th>
            <th></th>
            <th></th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @projects) do |project| %>
            <td><i class="fa fa-dot-circle-o" aria-hidden="true">
              <%= project.project_name %>
            </i></td>

            <td><i class="" aria-hidden="true">
              <%= project.address %>
            </i></td>

            <td><i class="fa fa-diamond" aria-hidden="true">
              <%= "#{project.rvm_list}@#{project.gemset}" %>
            </i></td>

            <td><i class="fa fa-eye" aria-hidden="true">
              <%= link_to 'Show', project %>
            </i></td>

            <td><i class="fa fa-pencil-square-o" aria-hidden="true">
              <%= link_to 'Edit', edit_project_path(project) %>
            </i></td>

            <td><i class="fa fa-trash-o" aria-hidden="true">
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
            </i></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show project</h1>
</div>

<dl class="dl-horizontal">
  <dt>Project name:</dt>
  <dd><%= @project.project_name %></dd>

  <dt>Address:</dt>
  <dd><%= @project.address %></dd>

  <dt>Rvm list:</dt>
  <dd><%= @project.rvm_list %></dd>

  <dt>Gemset:</dt>
  <dd><%= @project.gemset %></dd>

</dl>

app/views/services/_form.html.erb
<%= form_for(@service, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @service.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h4>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :projects, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :projects, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :status, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @service, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing service</h1>
</div>

<%= render 'form' %>

app/views/services/index.html.erb
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/v4-shims.css">
</head>
<div class="page-header">
  
  <h1>Listing services</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Projects</th>
            <th>Status</th>
      </tr>
    </thead>

    <tbody>
    <%#= raise @status.inspect %>
      <% @status.each do |key, value| %>
        <tr>
          <td><i class="fa fa-dot-circle-o" aria-hidden="true"><%= key %></i></td>
          <%if value == true %>
            <td class="on"><i class="fa fa-plug" aria-hidden="true"><%= 'On' %></i></td>
          <%else%>
            <td class="off"><i class="fa fa-power-off" aria-hidden="true"><%= 'Off' %></i></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/services/new.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New service</h1>
</div>

<%= render 'form' %>

app/views/services/show.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_service_path(@service), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show service</h1>
</div>

<dl class="dl-horizontal">
  <dt>Projects:</dt>
  <dd><%= @service.projects %></dd>

  <dt>Status:</dt>
  <dd><%= @service.status %></dd>

</dl>